name: Tests - disable-element

on:
  push:
    branches: [ main ]
    paths:
      - 'src/disable-element/**'
      - '.github/workflows/disable-element.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/disable-element/**'
      - '.github/workflows/disable-element.yml'
  workflow_dispatch:

jobs:
  test_suite:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        working-directory: ./src/disable-element
      - run: npm test
        working-directory: ./src/disable-element
